<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHyrlmI1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHyrlmI1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHyrlmI1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHyrlmI1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHyrlmI1\App_KernelDevDebugContainer([
    'container.build_hash' => 'HyrlmI1',
    'container.build_id' => 'b259727d',
    'container.build_time' => 1676723100,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHyrlmI1');
